name: Build and Push to ECR

on:
  workflow_call:
    inputs:
      aws-region:
        type: string
        required: false
        default: us-west-2
      ecr-repository:
        type: string
        required: true
    secrets:
      PAT_TOKEN:
        required: true
      AWS_ACCESS_KEY:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  check_organization:
    name: Check Organization
    runs-on: ubuntu-latest

    steps:
      - name: Check organization caller
        if: ${{ github.repository_owner != 'globaluy' }}
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('This workflow can only be used by Global')

  build_and_push:
    needs: check_organization
    name: Build and Push to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
          submodules: recursive

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws-region }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker environment
        uses: docker/setup-buildx-action@v2

      - name: Build, tag and push image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ inputs.ecr-repository }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker buildx b --progress plain --load -f ./dockerfile -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
