name: Check Organization

jobs:
  check_organization:
    name: Check Organization
    runs-on: ubuntu-latest

    steps:
      - name: Check organization caller
        if: ${{ github.repository_owner != 'globaluy' }}
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('This workflow can only be used by Global')
