name: SonarQube scan

on:
  workflow_call:
    inputs:
      node-version:
        type: string
        required: false
        default: 18.x
    secrets:
      PAT_TOKEN:
        required: false
      SONAR_HOST_URL:
        required: true
      SONAR_TOKEN:
        required: true

jobs:
  check_organization:
    name: Check organization
    uses: globaluy/workflows/.github/workflows/org.yml@v2.0.0

  sonarqube_scan:
    needs: check_organization
    name: SonarQube scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN || github.token }}
          submodules: recursive

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Execute tests
        run: npm run test:cov

      - name: SonarQube scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # - name: SonarQube quality gate
      #   uses: sonarsource/sonarqube-quality-gate-action@master
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
